version: 16
jobs:
- name: build
  jobExecutor: Server Shell Executor
  steps:
  - !CheckoutStep
    name: Checkout
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    condition: ALWAYS
  - !CommandStep
    name: build and start
    runInContainer: false
    interpreter: !ShellInterpreter
      shell: bash
      commands:
      - docker-compose build
      - docker-compose up -d
      - docker-compose ps
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !BranchUpdateTrigger
    branches: master
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  cpuRequirement: 250
  memoryRequirement: 256
  timeout: 3600
