version: 16
jobs:
- name: build
  steps:
  - !CheckoutStep
    name: Checkout
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    condition: ALWAYS
  - !CommandStep
    name: build and start
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands:
      - docker-compose build
      - docker-compose up -d
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  cpuRequirement: 250
  memoryRequirement: 256
  timeout: 3600
