version: 16
jobs:
- name: Build
  jobExecutor: karimi-hub
  steps:
  - !CheckoutStep
    name: Checkout
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    condition: ALWAYS
  - !CommandStep
    name: Build and Start
    runInContainer: true
    image: docker/compose
    interpreter: !ShellInterpreter
      shell: sh
      commands:
      - "@secret:environment_variables@ docker-compose build"
      - "@secret:environment_variables@ docker-compose up -d"
      - "@secret:environment_variables@ docker-compose ps"
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !BranchUpdateTrigger
    branches: master
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  cpuRequirement: 250
  memoryRequirement: 256
  timeout: 3600
